# Librerías: Numpy

Una de las ventajas de usar Python para procesar datos es la posibilidad de usar librerías.
Las librerías son colecciones de **módulos** que contienen **funciones** para ser usadas por otros programas (por ejemplo, nuestros notebooks y scripts).
Estas **funciones** suelen ahorrarnos mucho tiempo a la hora de realizar determinadas tareas, ya que no necesitamos escribir nuestro propio código para llevarlas a cabo.

Además, las librerías suelen están desarrolladas siguiendo las mejores prácticas:
- Código bien diseñado
- Utilizan controladores de versiones
- Poseen testeos automatizados
- Documentación extensiva
- Desarrolladas por una **comunidad**


En este notebook exploraremos una de las librerías más utilizadas a la hora de realizar computación científica: [**Numpy**](https://numpy.org).

## Importando librerías

Para poder hacer uso de las librerías, primero necesitamos **importarlas**.

In [1]:
import numpy

Esto nos permite acceder a los módulos y funciones de la librería. Por ejemplo, Numpy nos ofrece una función para calcular la media de una serie de valores:

In [2]:
numpy.mean([1, 2, 3, 4])

2.5

Muchas veces resulta tedioso escribir todo el nombre de la librería cada vez que queremos usar sus funciones o módulos.
Una opción es importarlas bajo un _alias_. Por ejemplo, NumPy se suele importar bajo el nombre `np`.

In [3]:
import numpy as np

np.mean([1, 2, 3, 4])

2.5

## Numpy arrays

NumPy introduce un nuevo tipo de variable, los `numpy.arrays` (o arreglos, en español).

Al igual que las listas, permiten guardar muchos valores bajo una única variable:

In [4]:
pares = np.array([2, 4, 6, 8])
print(pares)

[2 4 6 8]


In [5]:
type(pares)

numpy.ndarray

In [6]:
temperaturas = np.array([10.1, 14.6, 18.3, 20.3])
print(temperaturas)

[10.1 14.6 18.3 20.3]


Podemos usar los índices como lo hacíamos con las listas:

In [7]:
temperaturas[0]

10.1

In [8]:
temperaturas[2:]

array([18.3, 20.3])

Pero tienen sus diferencias:
- Los arrays tienen tamaño fijo. Una vez creados, no le podemos agregar o quitar valores.
- Los arrays almacenan un único tipo de variables (`floats` o `ints`).

Entonces, ¿por qué usar arrays?
- Manejo eficiente de la memoria.
- Todas las operaciones que realicemos con NumPy son más rápidas que usar _for loops_ y _lists_.

> **Usar Numpy arrays es como traer la velocidad de lenguajes compilados (FORTRAN, C, etc) a Python**

### Algunas funciones de Numpy

Ya vimos que podemos calcular la media de conjunto de valores a través de la función `np.mean`. Veamos cómo usar otras funciones:

La mediana:

In [9]:
np.median(temperaturas)

16.45

La desviación estándar:

In [10]:
np.std(temperaturas)

3.886756359742659

Valores máximos y mínimos:

In [11]:
print(np.min(temperaturas), np.max(temperaturas))

10.1 20.3


Cada vez que hagamos uso de las funciones de una librería, es recomendable leer su documentación. Por ejemplo, la documentación de la función `np.std` podemos hallarla en la [página web de Numpy](https://numpy.org/doc/stable/reference/generated/numpy.std.html).

Alternativamente, JupyterLab nos permite leer la documentación de cada una de estas funciones usando un signo de pregunta (`?`):

In [12]:
np.std?



## Ejercicio 1

con la finalidad de usar la libreria, 

teniendo el siguiente array [37 40 53 84 1 84 56 95 75 42 51 3 55 67 78 81 16 21 22 31 ] 

    1) Buscar el max y el minimo
       Nota: Se puede explorar la liberia y buscar las funciones que se necesiten. 
             Se puede usar xmin= np.min() y xmax= np.max() 
        
    2) Indique el lugar en que se encuentran el maximo y el minimo en el array
       Nota: Se puede igualmente explorar la libreria
             Pueden usar la funcion np.argmax() y np.argmin()
             La respuesta puede estar escrita asi: El maximo esta en la posicion *ii* y el minimo esta en la posicion *jj*
       


### Resolución

## Operaciones con arrays

Otra ventaja de usar arrays es que muchas operaciones matemáticas pueden realizarse muy facilmente. Por ejemplo, retomemos los valores de temperatura recibidos en Farenheit.

In [13]:
temperaturas_F = [30.3, 20.1, 46.5, 34.1, 42.3]

Convertimos la lista en un array:

In [14]:
temperaturas_F = np.array(temperaturas_F)
print(temperaturas_F)

[30.3 20.1 46.5 34.1 42.3]


Y convertimos a grados Celsius sencillamente:

In [15]:
temperaturas_C = (temperaturas_F - 32) * 5 / 9

In [16]:
print(temperaturas_C)

[-0.94444444 -6.61111111  8.05555556  1.16666667  5.72222222]


No solo podemos operar arrays con floats e ints, sino también con otros arrays:

In [17]:
precios = np.array([100, 200, 120, 98, 65, 3], dtype=float)
cantidades = np.array([2, 1, 3, 4, 9, 5])

In [18]:
print(precios)
print(cantidades)

[100. 200. 120.  98.  65.   3.]
[2 1 3 4 9 5]


In [19]:
costos = precios * cantidades
print(costos)

[200. 200. 360. 392. 585.  15.]


In [20]:
total = np.sum(costos)
print(total)

1752.0


Pero para que esto funcione, los arrays deben tener la misma **forma** (o formas compatibles).
Por ejemplo:

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## Arrays multidimensionales

Los arreglos que hemos utilizado hasta ahora son unidimensionales, pero es posible definir arreglos multidimensionales.
Por ejemplo, un arreglo 2D se vería como una matriz:

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

Podemos acceder a cada elemento de un arreglo 2D a través de sus índices:

In [ ]:
array_2d[0, 1]

O también podemos extraer una porción del array:

In [ ]:
array_2d[:, 1]

Podemos obtener la **forma** (`shape`) de cualquier array a través del **atributo** `shape`, la cual nos da información de cuántos elementos tiene en cada columna y en cada fila.

In [ ]:
array_2d.shape

> **Observación**
> - La **shape** de un array viene dada como una **tupla**, otra forma de ordenar valores (similar a una lista).
> - **No** podemos modificar el contenido de una tupla una vez creada.
> - Tampoco podemos agregar o quitarle elementos.

In [ ]:
shape = array_2d.shape
print(shape)

In [ ]:
type(shape)

In [ ]:
print(shape[0])
print(shape[1])

In [ ]:
shape[0] = 100

## Ejercicio 2

con la finalidad de usar la libreria,

Teniendo un array de esta forma ([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) 
    
    1) Reshape el array para que sea de 4x4
       Nota: Se puede explorar la liberia y buscar las funciones que se necesiten. 
             Se puede usar np.reshape (datos, (4,4))
    


### Resolución

## Funciones y constantes matemáticas 

Numpy nos permite también aplicar funciones matemáticas:

In [ ]:
np.sqrt(2)

In [ ]:
np.sin(np.pi / 2)

In [ ]:
np.cos(np.pi / 2)

In [ ]:
np.exp(1)

In [ ]:
np.log(np.e)

También podemos aplicarla a arrays y no solo a un único valor:

In [ ]:
cuadrados = np.array([4, 9, 16, 25, 36, 49, 64, 81])
np.sqrt(cuadrados)

## Ejercicio 3

1. Calcule el seno y el coseno de los angulos: 0, 30, 45, 60 y 90 dados en grados.
  1. Cree un array con los ángulos mencionados en grados.
  2. Convierta los ángulos a radianes. 
  3. Calcule el seno y el coseno de estos ángulos y guárdelos en dos arrays diferentes. 
     
    
> **Bonus Track**
> Haga uso de la función `np.radians` para convertir los ángulos en grados a radianes.



### Resolución